import type {QuoteTemplate} from './templateTypes';

export const LOCKSCREEN_TEMPLATES: QuoteTemplate[] = [
  // ==========================================
  // 1. MINIMAL LOCK SCREEN (5 templates)
  // ==========================================
  {
    id: 'lock_minimal_center_01',
    name: 'Quiet Horizon Lock',
    type: 'lockscreen',
    category: 'Minimal',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.2,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'OLED Battery Saver Minimal',
    accentColor: '#A1A1AA',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'lock_minimal_bottom_02',
    name: 'Bottom Anchored',
    type: 'lockscreen',
    category: 'Minimal',
    isPremium: false,
    layout: 'bottom',
    background: {type: 'solid', value: '#09090B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F4F4F5',
    },
    author: {
      visible: true,
      position: 'bottom-left',
      style: 'small',
      prefix: '— ',
      textColor: '#71717A',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Clear Safe Zone For Clock',
    accentColor: '#71717A',
    textColor: '#F4F4F5',
    authorColor: '#71717A',
  },
  {
    id: 'lock_authorless_zen_03',
    name: 'Zen Statement',
    type: 'lockscreen',
    category: 'Minimal',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#0A0A0C'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 17,
      lineHeight: 25,
      italic: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#E4E4E7',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'italic',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 24, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Authorless Zen Contemplation',
    accentColor: '#A1A1AA',
    textColor: '#E4E4E7',
    authorColor: '#71717A',
  },
  {
    id: 'lock_minimal_rule_04',
    name: 'Single Rule',
    type: 'lockscreen',
    category: 'Minimal',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#121214'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#EDEDED',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      textColor: '#71717A',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#3F3F46',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Understated Horizontal Rule',
    accentColor: '#71717A',
    textColor: '#EDEDED',
    authorColor: '#71717A',
  },
  {
    id: 'lock_minimal_serif_05',
    name: 'Quiet Bookmark',
    type: 'lockscreen',
    category: 'Minimal',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#18181B'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 24,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'single',
      alignment: 'center',
      textColor: '#F4F4F5',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Serif Reader Atmosphere',
    accentColor: '#A1A1AA',
    textColor: '#F4F4F5',
    authorColor: '#A1A1AA',
  },

  // ==========================================
  // 2. DARK & MIDNIGHT (5 templates)
  // ==========================================
  {
    id: 'lock_dark_abyss_01',
    name: 'OLED Abyss',
    type: 'lockscreen',
    category: 'Dark',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 16.5,
      lineHeight: 24,
      letterSpacing: -0.2,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#71717A',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Deep Pitch Black',
    accentColor: '#71717A',
    textColor: '#FFFFFF',
    authorColor: '#71717A',
  },
  {
    id: 'lock_midnight_indigo_02',
    name: 'Midnight Indigo',
    type: 'lockscreen',
    category: 'Dark',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#0F172A'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#F8FAFC',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#818CF8',
    },
    accent: {
      enabled: true,
      type: 'bar',
      color: '#6366F1',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Indigo Accent Bar',
    accentColor: '#818CF8',
    textColor: '#F8FAFC',
    authorColor: '#818CF8',
  },
  {
    id: 'lock_dark_mono_03',
    name: 'Hacker Prompt',
    type: 'lockscreen',
    category: 'Dark',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#0D1117'},
    typography: {
      fontFamily: 'mono',
      fontWeight: 'regular',
      fontSize: 14,
      lineHeight: 21,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#58A6FF',
    },
    author: {
      visible: true,
      position: 'above',
      style: 'small',
      prefix: '// DAILY INSTRUCTION: ',
      textColor: '#8B949E',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 20, quoteSpacing: 6, authorSpacing: 6},
    tagline: 'Monospace Developer Lock',
    accentColor: '#58A6FF',
    textColor: '#58A6FF',
    authorColor: '#8B949E',
  },
  {
    id: 'lock_dark_authorless_04',
    name: 'Dark Solitude',
    type: 'lockscreen',
    category: 'Dark',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#121214'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'bold',
      fontSize: 17,
      lineHeight: 24,
      letterSpacing: 0.5,
      uppercase: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'bold',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Authorless Capital Power',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'lock_charcoal_editorial_05',
    name: 'Charcoal Gazette',
    type: 'lockscreen',
    category: 'Dark',
    isPremium: true,
    layout: 'editorial',
    background: {type: 'solid', value: '#18181B'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#F4F4F5',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#3F3F46',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Editorial Midnight Edition',
    accentColor: '#A1A1AA',
    textColor: '#F4F4F5',
    authorColor: '#A1A1AA',
  },

  // ==========================================
  // 3. TYPOGRAPHY & BOLD (5 templates)
  // ==========================================
  {
    id: 'lock_bold_poster_01',
    name: 'Poster Impact Lock',
    type: 'lockscreen',
    category: 'Typography',
    isPremium: false,
    layout: 'poster',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'display',
      fontWeight: 'black',
      fontSize: 19,
      lineHeight: 25,
      letterSpacing: 1,
      uppercase: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'bold',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Heavyweight Morning Focus',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'lock_large_serif_02',
    name: 'Grand Serif',
    type: 'lockscreen',
    category: 'Typography',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#141416'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 17,
      lineHeight: 25,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'minimal',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'italic',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Grand Literary Presence',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'lock_quote_mark_03',
    name: 'Apostrophe Horizon',
    type: 'lockscreen',
    category: 'Typography',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#0A0A0C'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 24,
      italic: true,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#F5F5F4',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#78716C',
    },
    accent: {
      enabled: true,
      type: 'dot',
      color: '#D97706',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Centered Serif with Amber Dot',
    accentColor: '#D97706',
    textColor: '#F5F5F4',
    authorColor: '#78716C',
  },
  {
    id: 'lock_author_above_04',
    name: 'Top Voice Citation',
    type: 'lockscreen',
    category: 'Typography',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#18181B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FAFAFA',
    },
    author: {
      visible: true,
      position: 'above', // AUTHOR ABOVE QUOTE
      style: 'uppercase',
      prefix: 'INSIGHT FROM ',
      textColor: '#38BDF8',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Leading Author Header',
    accentColor: '#38BDF8',
    textColor: '#FAFAFA',
    authorColor: '#38BDF8',
  },
  {
    id: 'lock_bold_asymmetric_05',
    name: 'Asymmetric Edge',
    type: 'lockscreen',
    category: 'Typography',
    isPremium: true,
    layout: 'right',
    background: {type: 'solid', value: '#0F172A'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22.5,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'right',
      textColor: '#F8FAFC',
    },
    author: {
      visible: true,
      position: 'bottom-right',
      style: 'small',
      prefix: '— ',
      textColor: '#38BDF8',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Right-Docked Asymmetry',
    accentColor: '#38BDF8',
    textColor: '#F8FAFC',
    authorColor: '#38BDF8',
  },

  // ==========================================
  // 4. NATURE & ATMOSPHERE (5 templates)
  // ==========================================
  {
    id: 'lock_nature_mountain_01',
    name: 'Mountain Solitude',
    type: 'lockscreen',
    category: 'Nature',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#064E3B'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16.5,
      lineHeight: 24,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#ECFDF5',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#A7F3D0',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Deep Alpine Atmosphere',
    accentColor: '#A7F3D0',
    textColor: '#ECFDF5',
    authorColor: '#A7F3D0',
  },
  {
    id: 'lock_nature_ocean_mist_02',
    name: 'Pacific Dawn',
    type: 'lockscreen',
    category: 'Nature',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#0C4A6E'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F0FDFA',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#67E8F9',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Ocean Mist Tone',
    accentColor: '#67E8F9',
    textColor: '#F0FDFA',
    authorColor: '#67E8F9',
  },
  {
    id: 'lock_nature_forest_pine_03',
    name: 'Deep Evergreen',
    type: 'lockscreen',
    category: 'Nature',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#022C22'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23.5,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#D1FAE5',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'minimal',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 24, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Authorless Evergreen Calm',
    accentColor: '#6EE7B7',
    textColor: '#D1FAE5',
    authorColor: '#6EE7B7',
  },
  {
    id: 'lock_nature_desert_dusk_04',
    name: 'Terracotta Dusk',
    type: 'lockscreen',
    category: 'Nature',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#271A16'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23.5,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#FDEEE8',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#FB923C',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Warm Terracotta Glow',
    accentColor: '#FB923C',
    textColor: '#FDEEE8',
    authorColor: '#FB923C',
  },
  {
    id: 'lock_nature_starlight_05',
    name: 'Starry Midnight',
    type: 'lockscreen',
    category: 'Nature',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#070D18'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'regular',
      fontSize: 15.5,
      lineHeight: 23,
      letterSpacing: 0.2,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#E0F2FE',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      textColor: '#7DD3FC',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 6},
    tagline: 'Clear Cosmic Night',
    accentColor: '#7DD3FC',
    textColor: '#E0F2FE',
    authorColor: '#7DD3FC',
  },

  // ==========================================
  // 5. AESTHETIC & PAPER (6 templates)
  // ==========================================
  {
    id: 'lock_aesthetic_cream_01',
    name: 'Warm Cream Parchment',
    type: 'lockscreen',
    category: 'Aesthetic',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#FBF8F2'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16.5,
      lineHeight: 24,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#292524',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'italic',
      prefix: '— ',
      textColor: '#78716C',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Serene Warm Cream Tone',
    accentColor: '#292524',
    textColor: '#292524',
    authorColor: '#78716C',
  },
  {
    id: 'lock_aesthetic_paper_02',
    name: 'Antique Journal',
    type: 'lockscreen',
    category: 'Aesthetic',
    isPremium: false,
    layout: 'editorial',
    background: {type: 'solid', value: '#EFECE6'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 23.5,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#1C1917',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      suffix: ' · MOTIVA',
      textColor: '#57534E',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#D6D3D1',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Textured Book Tone',
    accentColor: '#1C1917',
    textColor: '#1C1917',
    authorColor: '#57534E',
  },
  {
    id: 'lock_aesthetic_authorless_03',
    name: 'Pure Canvas',
    type: 'lockscreen',
    category: 'Aesthetic',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#FAF9F6'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 23,
      letterSpacing: 0.1,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#09090B',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'minimal',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 24, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Authorless Neutral Canvas',
    accentColor: '#09090B',
    textColor: '#09090B',
    authorColor: '#71717A',
  },
  {
    id: 'lock_aesthetic_sage_04',
    name: 'Muted Sage',
    type: 'lockscreen',
    category: 'Aesthetic',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#E3E9E2'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22.5,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#1E2D24',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#4B6354',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Botanical Sage Palette',
    accentColor: '#1E2D24',
    textColor: '#1E2D24',
    authorColor: '#4B6354',
  },
  {
    id: 'lock_aesthetic_linen_05',
    name: 'Nordic Linen',
    type: 'lockscreen',
    category: 'Aesthetic',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#F2EFEB'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22.5,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#262626',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#737373',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Warm Neutral Minimalist',
    accentColor: '#262626',
    textColor: '#262626',
    authorColor: '#737373',
  },
  {
    id: 'lock_aesthetic_rose_06',
    name: 'Dusty Clay',
    type: 'lockscreen',
    category: 'Aesthetic',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#261D20'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FBE8EC',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'italic',
      prefix: '— ',
      textColor: '#F472B6',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Muted Rose Editorial',
    accentColor: '#F472B6',
    textColor: '#FBE8EC',
    authorColor: '#F472B6',
  },

  // ==========================================
  // 6. GLASS & PRODUCTIVITY (6 templates)
  // ==========================================
  {
    id: 'lock_glass_frosted_01',
    name: 'Floating Glass Panel',
    type: 'lockscreen',
    category: 'Glass',
    isPremium: true,
    layout: 'center',
    background: {
      type: 'glass',
      opacity: 0.55,
      blur: 24,
      borderColor: 'rgba(255, 255, 255, 0.18)',
      borderWidth: 1,
    },
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22.5,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: 'rgba(255, 255, 255, 0.7)',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 20,
      color: 'rgba(255, 255, 255, 0.2)',
      opacity: 0.2,
    },
    spacing: {padding: 20, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Translucent Lower Card',
    accentColor: 'rgba(255, 255, 255, 0.8)',
    textColor: '#FFFFFF',
    authorColor: 'rgba(255, 255, 255, 0.7)',
  },
  {
    id: 'lock_glass_dark_card_02',
    name: 'Obsidian Shield',
    type: 'lockscreen',
    category: 'Glass',
    isPremium: true,
    layout: 'left',
    background: {
      type: 'glass',
      opacity: 0.75,
      blur: 28,
      borderColor: 'rgba(255, 255, 255, 0.12)',
      borderWidth: 1,
    },
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 15,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'bottom-right',
      style: 'uppercase',
      prefix: '',
      textColor: '#A5B4FC',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 18,
      color: 'rgba(255, 255, 255, 0.15)',
      opacity: 0.15,
    },
    spacing: {padding: 18, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Dark Glass Inset',
    accentColor: '#A5B4FC',
    textColor: '#FFFFFF',
    authorColor: '#A5B4FC',
  },
  {
    id: 'lock_productivity_focus_03',
    name: 'Discipline Protocol',
    type: 'lockscreen',
    category: 'Productivity',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#18181B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'bold',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: 'MINDSET // ',
      textColor: '#10B981',
    },
    accent: {
      enabled: true,
      type: 'bar',
      color: '#10B981',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Emerald Productivity Bar',
    accentColor: '#10B981',
    textColor: '#FFFFFF',
    authorColor: '#10B981',
  },
  {
    id: 'lock_productivity_authorless_04',
    name: 'Execution First',
    type: 'lockscreen',
    category: 'Productivity',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#09090B'},
    typography: {
      fontFamily: 'display',
      fontWeight: 'bold',
      fontSize: 17.5,
      lineHeight: 24,
      letterSpacing: 0.8,
      uppercase: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'bold',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'No-Excuse Daily Action',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'lock_editorial_masthead_05',
    name: 'Morning Digest',
    type: 'lockscreen',
    category: 'Editorial',
    isPremium: true,
    layout: 'editorial',
    background: {type: 'solid', value: '#100E0D'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 23.5,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#F5F5F4',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '— ',
      textColor: '#A8A29E',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#292524',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Refined Morning Brief',
    accentColor: '#A8A29E',
    textColor: '#F5F5F4',
    authorColor: '#A8A29E',
  },
  {
    id: 'lock_developer_zen_06',
    name: 'SysAdmin Loop',
    type: 'lockscreen',
    category: 'Productivity',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#0A0E14'},
    typography: {
      fontFamily: 'mono',
      fontWeight: 'regular',
      fontSize: 14,
      lineHeight: 20,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#39BAE6',
    },
    author: {
      visible: true,
      position: 'above',
      style: 'small',
      prefix: '/* ',
      suffix: ' */',
      textColor: '#5C6773',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 20, quoteSpacing: 6, authorSpacing: 6},
    tagline: 'Developer Comment Syntax',
    accentColor: '#39BAE6',
    textColor: '#39BAE6',
    authorColor: '#5C6773',
  },

  // ==========================================
  // 7. LEGACY SEAMLESS COMPATIBILITY ALIASES
  // ==========================================
  {
    id: 'lock_minimal',
    name: 'Minimal Classic Lock',
    type: 'lockscreen',
    category: 'Minimal',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Timeless OLED Lock Screen',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'lock_midnight',
    name: 'Midnight Lock',
    type: 'lockscreen',
    category: 'Dark',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#0F172A'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 16,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#F8FAFC',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#818CF8',
    },
    border: {enabled: false, width: 0, radius: 24, color: 'transparent', opacity: 0},
    spacing: {padding: 22, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Midnight Indigo Calm',
    accentColor: '#818CF8',
    textColor: '#F8FAFC',
    authorColor: '#818CF8',
  },
];
