import type {QuoteTemplate} from './templateTypes';

export const WIDGET_TEMPLATES: QuoteTemplate[] = [
  // ==========================================
  // 1. MINIMAL COLLECTION (6 templates)
  // ==========================================
  {
    id: 'minimal_swiss_01',
    name: 'Swiss Pure',
    type: 'widget',
    category: 'Minimal',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#FFFFFF'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 16.5,
      lineHeight: 23,
      letterSpacing: -0.2,
      uppercase: false,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#0F172A',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#64748B',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 0, // Sharp architectural corners
      color: '#E2E8F0',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Swiss Minimalist',
    accentColor: '#0F172A',
    textColor: '#0F172A',
    authorColor: '#64748B',
  },
  {
    id: 'minimal_center_02',
    name: 'Quiet Center',
    type: 'widget',
    category: 'Minimal',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#09090B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
      letterSpacing: 0.1,
      uppercase: false,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#FAFAFA',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'minimal',
      prefix: '— ',
      textColor: '#71717A',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 12,
      color: '#27272A',
      opacity: 1,
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#3F3F46',
    },
    spacing: {padding: 18, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Deep Center Focus',
    accentColor: '#71717A',
    textColor: '#FAFAFA',
    authorColor: '#71717A',
  },
  {
    id: 'minimal_authorless_03',
    name: 'Pure Statement',
    type: 'widget',
    category: 'Minimal',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'bold',
      fontSize: 17,
      lineHeight: 24,
      letterSpacing: 1.2,
      uppercase: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'minimal',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 20, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Authorless Clarity',
    accentColor: '#A1A1AA',
    textColor: '#FFFFFF',
    authorColor: '#71717A',
  },
  {
    id: 'minimal_bottom_left_04',
    name: 'Anchored Edge',
    type: 'widget',
    category: 'Minimal',
    isPremium: false,
    layout: 'bottom',
    background: {type: 'solid', value: '#18181B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'regular',
      fontSize: 15,
      lineHeight: 22,
      letterSpacing: 0.2,
      uppercase: false,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#F4F4F5',
    },
    author: {
      visible: true,
      position: 'bottom-left',
      style: 'small',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 8,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Asymmetric Baseline',
    accentColor: '#A1A1AA',
    textColor: '#F4F4F5',
    authorColor: '#A1A1AA',
  },
  {
    id: 'minimal_monochrome_rule_05',
    name: 'Mono Rule',
    type: 'widget',
    category: 'Minimal',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#121214'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22,
      letterSpacing: 0,
      uppercase: false,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#E4E4E7',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      textColor: '#71717A',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#52525B',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 14,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Tracked Monochrome',
    accentColor: '#71717A',
    textColor: '#E4E4E7',
    authorColor: '#71717A',
  },
  {
    id: 'minimal_quiet_06',
    name: 'Quiet Horizon',
    type: 'widget',
    category: 'Minimal',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#0A0A0C'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 24,
      italic: true,
      uppercase: false,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#D4D4D8',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'italic',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 18,
      color: '#1F1F24',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Quiet Poetic Restraint',
    accentColor: '#A1A1AA',
    textColor: '#D4D4D8',
    authorColor: '#71717A',
  },

  // ==========================================
  // 2. TYPOGRAPHY & DISPLAY (5 templates)
  // ==========================================
  {
    id: 'typo_bold_poster_01',
    name: 'Bold Manifesto',
    type: 'widget',
    category: 'Typography',
    isPremium: false,
    layout: 'poster',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'display',
      fontWeight: 'black',
      fontSize: 18.5,
      lineHeight: 24,
      letterSpacing: 0.8,
      uppercase: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'bold',
    },
    border: {
      enabled: true,
      width: 2,
      radius: 0,
      color: '#FFFFFF',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'High Impact Poster',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'typo_giant_quotes_02',
    name: 'Garamond Quote',
    type: 'widget',
    category: 'Typography',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#18181B'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
      italic: false,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'minimal', // Giant quote mark above
      alignment: 'left',
      textColor: '#F4F4F5',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'italic',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    accent: {
      enabled: true,
      type: 'quote-mark',
      color: '#E4E4E7',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 6, authorSpacing: 8},
    tagline: 'Oversized Quotation',
    accentColor: '#E4E4E7',
    textColor: '#F4F4F5',
    authorColor: '#A1A1AA',
  },
  {
    id: 'typo_editorial_serif_03',
    name: 'Literary Press',
    type: 'widget',
    category: 'Typography',
    isPremium: true,
    layout: 'editorial',
    background: {type: 'solid', value: '#1E1B18'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
      italic: false,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#FAF5EE',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: 'BY ',
      textColor: '#D97706',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: 'rgba(217, 119, 6, 0.4)',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 12,
      color: '#2D2824',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Classic Publishing Tone',
    accentColor: '#D97706',
    textColor: '#FAF5EE',
    authorColor: '#D97706',
  },
  {
    id: 'typo_split_contrast_04',
    name: 'Split Tone',
    type: 'widget',
    category: 'Typography',
    isPremium: true,
    layout: 'split',
    background: {type: 'solid', value: '#0F172A'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 15.5,
      lineHeight: 22,
      letterSpacing: -0.1,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F8FAFC',
    },
    author: {
      visible: true,
      position: 'bottom-right',
      style: 'small',
      prefix: '',
      suffix: ' · MOTIQO',
      textColor: '#38BDF8',
    },
    accent: {
      enabled: true,
      type: 'bar',
      color: '#0284C7',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 14,
      color: '#1E293B',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Modern Split Composition',
    accentColor: '#38BDF8',
    textColor: '#F8FAFC',
    authorColor: '#38BDF8',
  },
  {
    id: 'typo_asymmetric_right_05',
    name: 'Right Aligned',
    type: 'widget',
    category: 'Typography',
    isPremium: false,
    layout: 'right',
    background: {type: 'solid', value: '#141416'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15,
      lineHeight: 21.5,
      letterSpacing: 0,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'right',
      textColor: '#E4E4E7',
    },
    author: {
      visible: true,
      position: 'bottom-right',
      style: 'small',
      prefix: '— ',
      textColor: '#818CF8',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Right Side Grid',
    accentColor: '#818CF8',
    textColor: '#E4E4E7',
    authorColor: '#818CF8',
  },

  // ==========================================
  // 3. GLASS & FROSTED (5 templates)
  // ==========================================
  {
    id: 'glass_dark_frosted_01',
    name: 'Dark Frost',
    type: 'widget',
    category: 'Glass',
    isPremium: false,
    layout: 'center',
    background: {
      type: 'glass',
      opacity: 0.65,
      blur: 20,
      borderColor: 'rgba(255, 255, 255, 0.16)',
      borderWidth: 1,
    },
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: 'rgba(255, 255, 255, 0.65)',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 18,
      color: 'rgba(255, 255, 255, 0.18)',
      opacity: 0.18,
    },
    spacing: {padding: 18, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Luminous Dark Glass',
    accentColor: 'rgba(255, 255, 255, 0.7)',
    textColor: '#FFFFFF',
    authorColor: 'rgba(255, 255, 255, 0.65)',
  },
  {
    id: 'glass_light_floating_02',
    name: 'Light Frost',
    type: 'widget',
    category: 'Glass',
    isPremium: true,
    layout: 'left',
    background: {
      type: 'glass',
      opacity: 0.8,
      blur: 24,
      borderColor: 'rgba(0, 0, 0, 0.1)',
      borderWidth: 1,
    },
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#0F172A',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#475569',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 20,
      color: 'rgba(0, 0, 0, 0.08)',
      opacity: 0.08,
    },
    spacing: {padding: 18, quoteSpacing: 10, authorSpacing: 8},
    tagline: 'Bright Translucent Surface',
    accentColor: '#0F172A',
    textColor: '#0F172A',
    authorColor: '#475569',
  },
  {
    id: 'glass_borderless_blur_03',
    name: 'Floating Sheen',
    type: 'widget',
    category: 'Glass',
    isPremium: true,
    layout: 'center',
    background: {
      type: 'glass',
      opacity: 0.45,
      blur: 30,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderWidth: 0.5,
    },
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#F8FAFC',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'minimal',
    },
    border: {
      enabled: true,
      width: 0.5,
      radius: 24,
      color: 'rgba(255, 255, 255, 0.12)',
      opacity: 0.12,
    },
    spacing: {padding: 20, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Authorless Glass Orb',
    accentColor: 'rgba(255, 255, 255, 0.8)',
    textColor: '#F8FAFC',
    authorColor: 'rgba(255, 255, 255, 0.6)',
  },
  {
    id: 'glass_author_pill_04',
    name: 'Glass Capsule',
    type: 'widget',
    category: 'Glass',
    isPremium: true,
    layout: 'left',
    background: {
      type: 'glass',
      opacity: 0.7,
      blur: 16,
      borderColor: 'rgba(255, 255, 255, 0.2)',
      borderWidth: 1,
    },
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15,
      lineHeight: 21,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'bottom-right',
      style: 'uppercase',
      prefix: '',
      textColor: '#A5B4FC',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: 'rgba(255, 255, 255, 0.22)',
      opacity: 0.22,
    },
    spacing: {padding: 16, quoteSpacing: 10, authorSpacing: 6},
    tagline: 'Tracked Glass Author',
    accentColor: '#A5B4FC',
    textColor: '#FFFFFF',
    authorColor: '#A5B4FC',
  },
  {
    id: 'glass_editorial_05',
    name: 'Editorial Glass',
    type: 'widget',
    category: 'Glass',
    isPremium: true,
    layout: 'editorial',
    background: {
      type: 'glass',
      opacity: 0.6,
      blur: 22,
      borderColor: 'rgba(255, 255, 255, 0.15)',
      borderWidth: 1,
    },
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
      italic: false,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: 'rgba(255, 255, 255, 0.75)',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: 'rgba(255, 255, 255, 0.2)',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 14,
      color: 'rgba(255, 255, 255, 0.15)',
      opacity: 0.15,
    },
    spacing: {padding: 18, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Serif on Frosted Card',
    accentColor: 'rgba(255, 255, 255, 0.75)',
    textColor: '#FFFFFF',
    authorColor: 'rgba(255, 255, 255, 0.75)',
  },

  // ==========================================
  // 4. TRANSPARENT (5 templates)
  // ==========================================
  {
    id: 'transparent_wallpaper_01',
    name: 'Pure Wallpaper',
    type: 'widget',
    category: 'Transparent',
    isPremium: false,
    layout: 'center',
    background: {type: 'transparent', opacity: 0},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 16.5,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: 'rgba(255, 255, 255, 0.85)',
    },
    border: {
      enabled: false,
      width: 0,
      radius: 0,
      color: 'transparent',
      opacity: 0,
    },
    spacing: {padding: 12, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Zero Card Overlay',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: 'rgba(255, 255, 255, 0.85)',
  },
  {
    id: 'transparent_authorless_02',
    name: 'Floating Words',
    type: 'widget',
    category: 'Transparent',
    isPremium: false,
    layout: 'center',
    background: {type: 'transparent', opacity: 0},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 17,
      lineHeight: 24,
      italic: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'italic',
    },
    border: {
      enabled: false,
      width: 0,
      radius: 0,
      color: 'transparent',
      opacity: 0,
    },
    spacing: {padding: 14, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Authorless Floating Serif',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'transparent_accent_bar_03',
    name: 'Luminous Line',
    type: 'widget',
    category: 'Transparent',
    isPremium: true,
    layout: 'left',
    background: {type: 'transparent', opacity: 0.15},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      textColor: '#38BDF8',
    },
    accent: {
      enabled: true,
      type: 'bar',
      color: '#38BDF8',
    },
    border: {
      enabled: false,
      width: 0,
      radius: 0,
      color: 'transparent',
      opacity: 0,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Cyan Side Accent',
    accentColor: '#38BDF8',
    textColor: '#FFFFFF',
    authorColor: '#38BDF8',
  },
  {
    id: 'transparent_minimal_bottom_04',
    name: 'Baseline Floating',
    type: 'widget',
    category: 'Transparent',
    isPremium: false,
    layout: 'bottom',
    background: {type: 'transparent', opacity: 0},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'regular',
      fontSize: 15,
      lineHeight: 21.5,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'bottom-left',
      style: 'small',
      prefix: '— ',
      textColor: 'rgba(255, 255, 255, 0.75)',
    },
    border: {
      enabled: false,
      width: 0,
      radius: 0,
      color: 'transparent',
      opacity: 0,
    },
    spacing: {padding: 12, quoteSpacing: 6, authorSpacing: 6},
    tagline: 'Bottom Anchored Overlay',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: 'rgba(255, 255, 255, 0.75)',
  },
  {
    id: 'transparent_corner_bracket_05',
    name: 'Architect Frame',
    type: 'widget',
    category: 'Transparent',
    isPremium: true,
    layout: 'center',
    background: {type: 'transparent', opacity: 0.1},
    typography: {
      fontFamily: 'mono',
      fontWeight: 'medium',
      fontSize: 14.5,
      lineHeight: 21,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#FAFAFA',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    accent: {
      enabled: true,
      type: 'corner',
      color: 'rgba(255, 255, 255, 0.45)',
    },
    border: {
      enabled: false,
      width: 0,
      radius: 0,
      color: 'transparent',
      opacity: 0,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Corner Framed Grid',
    accentColor: '#A1A1AA',
    textColor: '#FAFAFA',
    authorColor: '#A1A1AA',
  },

  // ==========================================
  // 5. EDITORIAL & MAGAZINE (5 templates)
  // ==========================================
  {
    id: 'editorial_no_01',
    name: 'The Review No. 1',
    type: 'widget',
    category: 'Editorial',
    isPremium: false,
    layout: 'editorial',
    background: {type: 'solid', value: '#1C1917'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 15.5,
      lineHeight: 22.5,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#F5F5F4',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '— ',
      textColor: '#A8A29E',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#44403C',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 12,
      color: '#292524',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Literary Journal',
    accentColor: '#D6D3D1',
    textColor: '#F5F5F4',
    authorColor: '#A8A29E',
  },
  {
    id: 'editorial_author_above_02',
    name: 'Top Citation',
    type: 'widget',
    category: 'Editorial',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#0F172A'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F8FAFC',
    },
    author: {
      visible: true,
      position: 'above', // AUTHOR ABOVE QUOTE
      style: 'uppercase',
      prefix: 'WORDS BY ',
      textColor: '#38BDF8',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#1E293B',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 6, authorSpacing: 6},
    tagline: 'Headline Citation Style',
    accentColor: '#38BDF8',
    textColor: '#F8FAFC',
    authorColor: '#38BDF8',
  },
  {
    id: 'editorial_magazine_asym_03',
    name: 'Harper Column',
    type: 'widget',
    category: 'Editorial',
    isPremium: true,
    layout: 'magazine',
    background: {type: 'solid', value: '#FAF8F5'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'semibold',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#1C1917',
    },
    author: {
      visible: true,
      position: 'bottom-right',
      style: 'italic',
      prefix: '— ',
      textColor: '#78716C',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 8,
      color: '#E7E5E4',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Warm Cream Column',
    accentColor: '#1C1917',
    textColor: '#1C1917',
    authorColor: '#78716C',
  },
  {
    id: 'editorial_authorless_journal_04',
    name: 'Book Excerpt',
    type: 'widget',
    category: 'Editorial',
    isPremium: false,
    layout: 'editorial',
    background: {type: 'solid', value: '#121214'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 23.5,
      italic: false,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#E4E4E7',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'small',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 12,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 6, authorSpacing: 0},
    tagline: 'Uncredited Excerpt',
    accentColor: '#A1A1AA',
    textColor: '#E4E4E7',
    authorColor: '#71717A',
  },
  {
    id: 'editorial_split_rule_05',
    name: 'Gazette Rule',
    type: 'widget',
    category: 'Editorial',
    isPremium: true,
    layout: 'split',
    background: {type: 'solid', value: '#0C0A09'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 15,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F5F5F4',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      suffix: ' // ISSUE 01',
      textColor: '#D97706',
    },
    accent: {
      enabled: true,
      type: 'line',
      color: '#292524',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 0,
      color: '#1C1917',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Architectural Masthead',
    accentColor: '#D97706',
    textColor: '#F5F5F4',
    authorColor: '#D97706',
  },

  // ==========================================
  // 6. DARK & MONOCHROME (5 templates)
  // ==========================================
  {
    id: 'dark_deep_charcoal_01',
    name: 'Charcoal Minimal',
    type: 'widget',
    category: 'Dark',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#121214'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#EDEDED',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#888888',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 12,
      color: '#262626',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Low-Distraction Charcoal',
    accentColor: '#888888',
    textColor: '#EDEDED',
    authorColor: '#888888',
  },
  {
    id: 'dark_accent_line_02',
    name: 'Amber Glow Line',
    type: 'widget',
    category: 'Dark',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#09090B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F4F4F5',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#F59E0B',
    },
    accent: {
      enabled: true,
      type: 'bar',
      color: '#F59E0B',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 14,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Amber Vertical Accent',
    accentColor: '#F59E0B',
    textColor: '#F4F4F5',
    authorColor: '#F59E0B',
  },
  {
    id: 'dark_mono_code_03',
    name: 'Console Terminal',
    type: 'widget',
    category: 'Dark',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#0D1117'},
    typography: {
      fontFamily: 'mono',
      fontWeight: 'regular',
      fontSize: 14,
      lineHeight: 20,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#E6EDF3',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '// Author: ',
      textColor: '#7EE787',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 10,
      color: '#30363D',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Code Syntax Style',
    accentColor: '#7EE787',
    textColor: '#E6EDF3',
    authorColor: '#7EE787',
  },
  {
    id: 'dark_authorless_brutal_04',
    name: 'Brutalist Contrast',
    type: 'widget',
    category: 'Dark',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'bold',
      fontSize: 17,
      lineHeight: 23,
      letterSpacing: -0.3,
      uppercase: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'bold',
    },
    border: {
      enabled: true,
      width: 2,
      radius: 0,
      color: '#333333',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Sharp Monochrome Edge',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    authorColor: '#888888',
  },
  {
    id: 'dark_slate_card_05',
    name: 'Slate Minimal',
    type: 'widget',
    category: 'Dark',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#1E293B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#F8FAFC',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#94A3B8',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#334155',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Subtle Slate Horizon',
    accentColor: '#94A3B8',
    textColor: '#F8FAFC',
    authorColor: '#94A3B8',
  },

  // ==========================================
  // 7. AESTHETIC & LIGHT (5 templates)
  // ==========================================
  {
    id: 'aesthetic_warm_beige_01',
    name: 'Warm Linen',
    type: 'widget',
    category: 'Aesthetic',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#F7F4EE'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#292524',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'italic',
      prefix: '— ',
      textColor: '#78716C',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 14,
      color: '#E7E5E4',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Warm Earthy Texture',
    accentColor: '#292524',
    textColor: '#292524',
    authorColor: '#78716C',
  },
  {
    id: 'aesthetic_paper_minimal_02',
    name: 'Newsprint Paper',
    type: 'widget',
    category: 'Aesthetic',
    isPremium: false,
    layout: 'editorial',
    background: {type: 'solid', value: '#EFECE6'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'left',
      textColor: '#1C1917',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      textColor: '#57534E',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 6,
      color: '#D6D3D1',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 8},
    tagline: 'Authentic Paper Feel',
    accentColor: '#1C1917',
    textColor: '#1C1917',
    authorColor: '#57534E',
  },
  {
    id: 'aesthetic_authorless_pure_03',
    name: 'White Gallery',
    type: 'widget',
    category: 'Aesthetic',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#FFFFFF'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
      letterSpacing: 0.1,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#09090B',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'minimal',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 18,
      color: '#F4F4F5',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Art Gallery White Space',
    accentColor: '#09090B',
    textColor: '#09090B',
    authorColor: '#71717A',
  },
  {
    id: 'aesthetic_serif_italic_04',
    name: 'Quiet Poet',
    type: 'widget',
    category: 'Aesthetic',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#FFFDF9'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 23.5,
      italic: true,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'single',
      alignment: 'center',
      textColor: '#292524',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#A8A29E',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#E7E5E4',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Gentle Poetic Rhythm',
    accentColor: '#292524',
    textColor: '#292524',
    authorColor: '#A8A29E',
  },
  {
    id: 'aesthetic_coffee_card_05',
    name: 'Espresso Roast',
    type: 'widget',
    category: 'Aesthetic',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#241E1C'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15,
      lineHeight: 21.5,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F5EBE6',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: '',
      textColor: '#D97706',
    },
    accent: {
      enabled: true,
      type: 'dot',
      color: '#D97706',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 12,
      color: '#3B312E',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Deep Warm Tones',
    accentColor: '#D97706',
    textColor: '#F5EBE6',
    authorColor: '#D97706',
  },

  // ==========================================
  // 8. NATURE, PRODUCTIVITY & DEV (6 templates)
  // ==========================================
  {
    id: 'nature_mountain_dawn_01',
    name: 'Alpine Pine',
    type: 'widget',
    category: 'Nature',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#064E3B'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#ECFDF5',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#6EE7B7',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#065F46',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Evergreen Stillness',
    accentColor: '#6EE7B7',
    textColor: '#ECFDF5',
    authorColor: '#6EE7B7',
  },
  {
    id: 'nature_ocean_calm_02',
    name: 'Deep Pacific',
    type: 'widget',
    category: 'Nature',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#0C4A6E'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#F0FDF4',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#38BDF8',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#0369A1',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Oceanic Horizon',
    accentColor: '#38BDF8',
    textColor: '#F0FDF4',
    authorColor: '#38BDF8',
  },
  {
    id: 'nature_forest_authorless_03',
    name: 'Forest Canopy',
    type: 'widget',
    category: 'Nature',
    isPremium: true,
    layout: 'center',
    background: {type: 'solid', value: '#022C22'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 23,
      italic: true,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'center',
      textColor: '#D1FAE5',
    },
    author: {
      visible: false, // AUTHORLESS
      position: 'below',
      style: 'italic',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 14,
      color: '#064E3B',
      opacity: 1,
    },
    spacing: {padding: 18, quoteSpacing: 0, authorSpacing: 0},
    tagline: 'Calm Sanctuary',
    accentColor: '#6EE7B7',
    textColor: '#D1FAE5',
    authorColor: '#6EE7B7',
  },
  {
    id: 'productivity_focus_bar_04',
    name: 'Focus Block',
    type: 'widget',
    category: 'Productivity',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#18181B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'bold',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'uppercase',
      prefix: 'TARGET // ',
      textColor: '#E11D48',
    },
    accent: {
      enabled: true,
      type: 'bar',
      color: '#E11D48',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 8,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'High Focus Intensity',
    accentColor: '#E11D48',
    textColor: '#FFFFFF',
    authorColor: '#E11D48',
  },
  {
    id: 'productivity_deep_work_05',
    name: 'Deep Work Matrix',
    type: 'widget',
    category: 'Productivity',
    isPremium: true,
    layout: 'editorial',
    background: {type: 'solid', value: '#09090B'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 15,
      lineHeight: 21,
      letterSpacing: -0.2,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#F4F4F5',
    },
    author: {
      visible: true,
      position: 'bottom-right',
      style: 'small',
      prefix: '',
      suffix: ' · DEEP WORK',
      textColor: '#A1A1AA',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 12,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Structured Routine',
    accentColor: '#A1A1AA',
    textColor: '#F4F4F5',
    authorColor: '#A1A1AA',
  },
  {
    id: 'developer_terminal_06',
    name: 'Bash Kernel',
    type: 'widget',
    category: 'Developer',
    isPremium: true,
    layout: 'left',
    background: {type: 'solid', value: '#0D1117'},
    typography: {
      fontFamily: 'mono',
      fontWeight: 'medium',
      fontSize: 13.5,
      lineHeight: 19.5,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#58A6FF',
    },
    author: {
      visible: true,
      position: 'above',
      style: 'small',
      prefix: '$ git commit -m "',
      suffix: '"',
      textColor: '#8B949E',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 8,
      color: '#21262D',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 6, authorSpacing: 4},
    tagline: 'Developer Terminal',
    accentColor: '#58A6FF',
    textColor: '#58A6FF',
    authorColor: '#8B949E',
  },

  // ==========================================
  // 9. LEGACY SEAMLESS COMPATIBILITY ALIASES
  // ==========================================
  {
    id: 'widget_midnight',
    name: 'Midnight Modern',
    type: 'widget',
    category: 'Dark',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#0F172A'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 16,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#F8FAFC',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#94A3B8',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 18,
      color: 'rgba(99, 102, 241, 0.25)',
      opacity: 0.25,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Deep Midnight Indigo',
    accentColor: '#818CF8',
    textColor: '#F8FAFC',
    authorColor: '#94A3B8',
  },
  {
    id: 'widget_minimal_black',
    name: 'Minimal Black',
    type: 'widget',
    category: 'Minimal',
    isPremium: false,
    layout: 'center',
    background: {type: 'solid', value: '#000000'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'medium',
      fontSize: 16,
      lineHeight: 23,
    },
    quote: {
      showQuoteMarks: true,
      quoteMarkStyle: 'double',
      alignment: 'center',
      textColor: '#FFFFFF',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#A1A1AA',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#27272A',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Pure OLED Black',
    accentColor: '#71717A',
    textColor: '#FFFFFF',
    authorColor: '#A1A1AA',
  },
  {
    id: 'widget_minimal_white',
    name: 'Minimal White',
    type: 'widget',
    category: 'Light',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#FFFFFF'},
    typography: {
      fontFamily: 'sans',
      fontWeight: 'semibold',
      fontSize: 16,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#0F172A',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'small',
      prefix: '— ',
      textColor: '#64748B',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#E2E8F0',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Clean Slate On White',
    accentColor: '#6366F1',
    textColor: '#0F172A',
    authorColor: '#64748B',
  },
  {
    id: 'widget_soft_beige',
    name: 'Soft Beige',
    type: 'widget',
    category: 'Aesthetic',
    isPremium: false,
    layout: 'left',
    background: {type: 'solid', value: '#F5F5F0'},
    typography: {
      fontFamily: 'serif',
      fontWeight: 'medium',
      fontSize: 15.5,
      lineHeight: 22,
    },
    quote: {
      showQuoteMarks: false,
      quoteMarkStyle: 'none',
      alignment: 'left',
      textColor: '#292524',
    },
    author: {
      visible: true,
      position: 'below',
      style: 'italic',
      prefix: '— ',
      textColor: '#78716C',
    },
    border: {
      enabled: true,
      width: 1,
      radius: 16,
      color: '#E7E5E4',
      opacity: 1,
    },
    spacing: {padding: 16, quoteSpacing: 8, authorSpacing: 6},
    tagline: 'Warm Earthy Beige',
    accentColor: '#D97706',
    textColor: '#292524',
    authorColor: '#78716C',
  },
];
